# This is a basic workflow to help you get started with Actions
name: Build, Test and Deploy Among Us Discord Bot to GitHub Registry

# Controls when the action will run.
on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

  workflow_dispatch:

jobs:
  Security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  push_to_registry:
    needs: Security
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
            context: .
            push: true
            tags: ${{env.REGISTRY}}/r3dau/yetanothertwitchbot:latest

  #update-portainer:
  #  needs: push_to_registry
  #  #runs-on: [ self-hosted ]
  #  steps:
  #    - name: Update container in Portainer
  #      run: |
  #        curl -s -k -X POST ${{ secrets.PORTAINER_URL }}